const LoanRequestData = [
    {
        id: 1,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 2,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 3,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 4,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 5,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 6,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Project Finance',
        details: 'View details',
    },
    {
        id: 7,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finances',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 8,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
    {
        id: 9,
        offerName: 'Rice Value Chain',
        imageUrl: 'https://res.cloudinary.com/sophire/image/upload/v1643039524/orderbook/Downloader_9_djpbtv.png',
        category: 'Project Finance',
        desc: 'Rice is the most consumed commodity. Total global rice expenditure in 2020 was $350 billion. To put in perspective, totoal global crude oil in 2020 was just four times that amount at $1.3 trillion.',
        details: 'View details',
    },
];
export default LoanRequestData;
