export const offers = [
	{
		name: "Rice Chain Value",
		tranche: "Tranche 1",
		tenor: "90 days",
		size: "NGN 10 Million",
		status: "Bid Approved",
	},
	{
		name: "Agrix",
		tranche: "Tranche 2",
		tenor: "50 days",
		size: "USD 1 Million",
		status: "Bid Rejected",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 3",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Coming soon",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 4",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "Agrix",
		tranche: "Tranche 5",
		tenor: "50 days",
		size: "USD 1 Million",
		status: "Coming soon",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 6",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Offer open",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 7",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Coming soon",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 8",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Offer open",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 9",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Coming soon",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 7",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 8",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Coming soon",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 9",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 7",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 8",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Coming soon",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 9",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 7",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 8",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Coming soon",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 9",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "TribeModern Realty",
		tranche: "Tranche 7",
		tenor: "50 days",
		size: "NGN 10 Million",
		status: "Offer open",
	},
	{
		name: "Trinster startup",
		tranche: "Tranche 8",
		tenor: "50 days",
		size: "NGN 1 Billion",
		status: "Coming soon",
	}
];